apiVersion: 1
datasources:
  - name: "Thanos"
    type: prometheus
    uid: "thanos-main"
    url: "http://thanos-querier.monitoring.svc.cluster.local:9090"
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - datasourceUid: "tempo"
          name: "traceID"
      cacheLevel: "none"
    version: 1
