version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - SB_URL=${SB_URL}
      - SB_TOKEN=${SB_TOKEN}
      - SB_SECRET_KEY=${SB_SECRET_KEY}
      - SB_JWT_SECRET=${SB_JWT_SECRET}
      - SB_PUB_KEY=${SB_PUB_KEY}
      - SB_DATA_URL=${SB_DATA_URL}
      - RUNTIME_MODE=api
    volumes:
      - dag-events:/tmp/dag_events

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - SB_URL=${SB_URL}
      - SB_TOKEN=${SB_TOKEN}
      - SB_SECRET_KEY=${SB_SECRET_KEY}
      - SB_JWT_SECRET=${SB_JWT_SECRET}
      - SB_PUB_KEY=${SB_PUB_KEY}
      - SB_DATA_URL=${SB_DATA_URL}
      - RUNTIME_MODE=worker
      - SB_WORKER_NODES=http://worker:8080
    volumes:
      - dag-events:/tmp/dag_events
    deploy:
      replicas: 2

volumes:
  dag-events:
