apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simhpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: simhpc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simhpc-backend
            port:
              number: 8000
