name: Deploy Supabase

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy to Production
        env:
          SB_ACCESS_TOKEN: ${{ secrets.SB_ACCESS_TOKEN }}
          SB_PROJECT_ID: ${{ secrets.SB_PROJECT_ID }}
          SB_DB_PASSWORD: ${{ secrets.SB_DB_PASSWORD }}
        run: |
          supabase login --token "$SB_ACCESS_TOKEN"
          supabase link --project-ref "$SB_PROJECT_ID" --password "$SB_DB_PASSWORD"
          supabase db push --password "$SB_DB_PASSWORD"
          supabase functions deploy --project-ref "$SB_PROJECT_ID"