import io

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


class PDFReportService:
    @staticmethod
    def generate_certificate_pdf(cert_data: dict, sim_data: dict):
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=LETTER)
        width, height = LETTER

        # 1. Header & Branding
        c.setFillColor(colors.HexColor("#0891b2"))  # Mercury Cyan
        c.rect(0, height - 1.5 * inch, width, 1.5 * inch, fill=1, stroke=0)

        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 24)
        c.drawString(1 * inch, height - 1 * inch, "SimHPC: VERIFIED SIMULATION REPORT")

        # 2. Certificate Info
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(1 * inch, height - 2 * inch, f"Certificate ID: {cert_data['certificate_id']}")
        c.setFont("Helvetica", 10)
        c.drawString(1 * inch, height - 2.2 * inch, f"Issued At: {cert_data['issued_at']}")

        # 3. Cryptographic Proof (The Moat)
        c.setStrokeColor(colors.lightgrey)
        c.roundRect(0.8 * inch, height - 3.2 * inch, 6.4 * inch, 0.7 * inch, 4, stroke=1, fill=0)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1 * inch, height - 2.7 * inch, "SHA-256 DIGITAL SIGNATURE")
        c.setFont("Courier", 8)
        c.drawString(1 * inch, height - 2.9 * inch, cert_data["signature_hash"])

        # 4. Simulation Summary
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1 * inch, height - 4 * inch, "Simulation Results Summary")

        y_offset = height - 4.3 * inch
        c.setFont("Helvetica", 10)
        results = sim_data.get("result_summary", {})
        if isinstance(results, dict):
            for key, value in results.items():
                c.drawString(1.2 * inch, y_offset, f"• {str(key).replace('_', ' ').title()}: {str(value)}")
                y_offset -= 0.2 * inch

        # 5. The Verification QR Code
        verify_url = f"https://simhpc.com/verify/{cert_data['certificate_id']}"
        qr = qrcode.make(verify_url)
        qr_img_buffer = io.BytesIO()
        qr.save(qr_img_buffer, format="PNG")
        qr_img_buffer.seek(0)

        c.drawImage(qr_img_buffer, width - 2.5 * inch, 1 * inch, width=1.5 * inch, height=1.5 * inch)
        c.setFont("Helvetica-Oblique", 8)
        c.drawCentredString(width - 1.75 * inch, 0.8 * inch, "Scan to verify integrity")

        # 6. Footer
        c.setFont("Helvetica", 8)
        c.setFillColor(colors.grey)
        c.drawCentredString(
            width / 2,
            0.5 * inch,
            "This document is an immutable record generated by SimHPC Core Orchestrator v2.5.0.",
        )

        c.showPage()
        c.save()
        buffer.seek(0)
        return buffer
