version: "3.9"

services:
  kernel:
    environment:
      - GPU_WORKER_HOST=gpu-worker.simhpc-simulation
      - GPU_WORKER_PORT=50053
    networks:
      - simhpc-control
      - simhpc-reasoning
      - simhpc-simulation

  gpu-worker:
    extends:
      file: docker-compose.gpu.yml
      service: gpu-worker
    networks:
      - simhpc-simulation

networks:
  simhpc-control:
    driver: overlay
    attachable: true
  simhpc-reasoning:
    driver: overlay
    attachable: true
    internal: true
  simhpc-simulation:
    driver: overlay
    attachable: true
    internal: true
