import LegalLayout from './LegalLayout';

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service">
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200">1. Services Provided</h2>
        <p>SimHPC provides high-performance computing simulation tools. We reserve the right to modify or discontinue features to maintain system integrity and performance.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200">2. High-Performance Computing (HPC) Usage</h2>
        <p>Users agree not to use SimHPC for crypto-mining, DDoS attacks, or any activity that stresses the shared infrastructure beyond reasonable simulation limits.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200">3. Limitation of Liability</h2>
        <p>SimHPC is for analytical purposes. Results are simulated and do not constitute a guarantee of real-world physical performance or safety for athletes or equipment.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200">4. Account Responsibilities</h2>
        <p>Users are responsible for maintaining the security of their account credentials. SimHPC is not liable for unauthorized access resulting from user negligence.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200">5. Intellectual Property</h2>
        <p>All simulation outputs, reports, and notebook entries generated by users remain the intellectual property of the user. SimHPC claims no ownership over user-generated content.</p>
      </section>
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200">6. Termination</h2>
        <p>SimHPC reserves the right to suspend or terminate accounts that violate these terms or abuse platform resources.</p>
      </section>
    </LegalLayout>
  );
}
