apiVersion: batch/v1
kind: Job
metadata:
  name: simhpc-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "-m", "backend.scripts.run_migrations"]
      restartPolicy: Never
  backoffLimit: 3
