# {{- if .Values.thanos.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: monitoring
type: Opaque
stringData:
  config: |
    type: s3
    config:
      bucket: {{ .Values.thanos.s3.bucket | quote }}
      endpoint: "s3.us-east-1.amazonaws.com"
      region: "us-east-1"
      access_key: {{ .Values.thanos.s3.accessKey | quote }}
      secret_key: {{ .Values.thanos.s3.secretKey | quote }}
{{- end }}
