FROM nvidia/cuda:12.1.0-base-ubuntu22.04

RUN apt-get update && apt-get install -y python3 python3-pip curl

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir runpod mfem numpy

ENV PYTHONPATH=/app

CMD ["python3", "-u", "/app/handler.py"]
