#!/usr/bin/env python3
"""
Lockfile enforcement:
Ensures requirements.*.lock files are in sync with pyproject.toml.
"""

import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]  # Project Root
BACKEND = ROOT / "backend"


def run(cmd: list[str]) -> int:
    result = subprocess.run(
        cmd,
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stderr)
    return result.returncode


def get_content_hash(path: Path) -> str:
    # Skip all comments (including the autogenerated header with filename/paths)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
        content = "\n".join([line for line in lines if not line.strip().startswith("#")])
        return hashlib.sha256(content.encode("utf-8")).hexdigest()
    except Exception:
        return ""


def compile_lock(extra: str | None, output: Path) -> int:
    # Run from ROOT, pyproject.toml is at ROOT
    cmd = ["uv", "pip", "compile", "pyproject.toml", "-o", str(output)]

    if extra:
        cmd.insert(3, "--extra")
        cmd.insert(4, extra)

    return run(cmd)


def check(lock_name: str, extra: str | None):
    print(f"[LOCK] Checking {lock_name}")

    existing = BACKEND / lock_name

    if not existing.exists():
        print(f"[LOCK] Missing {existing.resolve()}")
        sys.exit(1)

    with tempfile.NamedTemporaryFile(suffix=".lock", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        ret = compile_lock(extra, tmp_path)
        if ret != 0:
            print(f"[LOCK] SKIP: Could not compile lockfile (build tools missing? Exit code {ret})")
            return

        if get_content_hash(existing) != get_content_hash(tmp_path):
            print(f"\n[LOCK] Drift detected in {lock_name}")
            import difflib

            existing_lines = existing.read_text().splitlines()
            tmp_lines = tmp_path.read_text().splitlines()
            diff = difflib.unified_diff(existing_lines, tmp_lines, lineterm="")
            print("\n".join(diff))

            print("Run:")
            if extra:
                print(f"  uv pip compile pyproject.toml --extra {extra} -o backend/{lock_name}")
            else:
                print(f"  uv pip compile pyproject.toml -o backend/{lock_name}")
            sys.exit(1)

        print(f"[LOCK] OK: {lock_name}")

    finally:
        tmp_path.unlink(missing_ok=True)


def main():
    check("requirements.api.lock", None)
    check("requirements.worker.lock", "worker")
    check("requirements.dev.lock", "dev")

    print("\n[LOCK] All lockfiles in sync")


if __name__ == "__main__":
    main()
