apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simhpc.fullname" . }}-config
  labels:
    {{- include "simhpc.labels" . | nindent 4 }}
data:
  RUNTIME_MODE: {{ .Values.env.RUNTIME_MODE | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
