image:
  repository: ghcr.io/simhpc/core
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 3

namespace: simhpc

# Core configuration
supabase:
  url: ""
  key: ""

infisical:
  clientId: ""
  clientSecret: ""
  projectId: ""

kata:
  enabled: false

monitoring:
  thanos:
    enabled: true
  falco:
    enabled: true
  sysdig:
    enabled: true

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "4"
    memory: "8Gi"
