apiVersion: v2
name: simhpc
description: SimHPC World Brain - Simulation Intelligence Platform
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - simulation
  - ai
  - fastapi
  - redis
  - minikube
maintainers:
  - name: neXusEvents
    email: your-email@example.com