replicaCount: 2

image:
  repository: simhpc/backend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: simhpc.local

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

env:
  RUNTIME_MODE: production

redis:
  enabled: true
  architecture: replication
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 10Gi
  replica:
    persistence:
      enabled: true
      size: 10Gi
  metrics:
    enabled: true

minikube:
  enabled: true
